#!/usr/bin/env python3
"""gen_data_pages.py — programmatic SEO for the attested-data catalog.

Emits one deep, real landing page per dataset SKU from a data manifest — no
LLM, no GPU. Every fact on the page comes from the signed artifacts. Each
page carries schema.org/Dataset + FAQPage JSON-LD so it is eligible for
Google Dataset Search and FAQ rich results — the honest, compounding traffic
channel for training-data buyers.

Adding a SKU = one entry in CATALOG below, rerun, redeploy. Also writes a
machine-readable /data/catalog.json (agent-shoppable) and prints the sitemap
<url> block to paste.

Run: python3 tools/gen_data_pages.py   (from repo root)
Out: data/<slug>.html, data/catalog.json
"""
import json
import os

SITE = "https://ledatic.org"
OUT = os.path.join(os.path.dirname(__file__), "..", "data")

CATALOG = [
    {
        "slug": "rail-verified-pairs-v2",
        "name": "Rail Verified-Pairs Corpus v2",
        "price_usd": 199,
        "pack": "pairs",
        "tagline": "52,243 oracle-verified comment→program pairs. Every program compiles — re-verifiable by you.",
        "kicker": "Code training data · oracle-verified · bit-reproducible",
        "records": "52,243 pairs",
        "size_h": "4.4 MB (JSONL)",
        "format": "application/jsonl",
        "sha256": "1a6941afad3ad6259af6a0a48f0554108ba0b3197e8e05e53e487833a6cd046c",
        "pulse": 2641877,
        "provenance": "operated-substrate (synthetic, machine-verified)",
        "provenance_long": "Every program was generated by our own generator and verified by running the Rail compiler (the oracle) on it. No scraped code, no license ambiguity, no human-authored third-party code.",
        "buy_url": "https://buy.stripe.com/6oU28j5cBbsDaoC3lN0Fi03",
        "sample": "/data/rail-verified-pairs-v2-sample200.jsonl",
        "ledger": "/data/rail-verified-pairs-v2.ledger.sig.json",
        "keywords": ["rail training data", "oracle-verified code dataset", "compiling code training pairs", "provenance training data", "bit-reproducible dataset", "attested training data"],
        "highlights": [
            "52,243 comment→program pairs; <strong>every one compiles</strong> under the public Rail compiler",
            "Bit-reproducible: generator + seed 1234 + oracle ⇒ byte-identical file",
            "This exact file trained a from-scratch 138M model to 16/16 compile@1 on a frozen benchmark",
            "Signed provenance chain (Ed25519 witness at public entropy pulse 2641877) ships in the box",
        ],
        "faq": [
            ("Is this scraped code?", "No. Every program is synthetically generated and then verified by running the Rail compiler on it. There is no scraped or third-party human-authored code, so there is no license ambiguity."),
            ("How do I verify the dataset before trusting it?", "A 200-pair sample, the signed ledger, and the tarball hash are free downloads. After purchase, the included verify_pairs.py re-checks that (1) the file's SHA-256 matches the hash bound in the signed training ledger and (2) every one of the 52,243 programs compiles under the public oracle."),
            ("What does bit-reproducible mean here?", "Running the included generator with seed 1234 against the same oracle produces a byte-identical corpus. We regenerated it twice to confirm. You can reproduce it yourself."),
            ("What license do I get?", "A single-organization commercial license: train and ship models freely, including commercially, with no royalty. You may not redistribute the dataset itself. See LICENSE.md in the package."),
            ("What model result backs this?", "The included hash-chained ledger records a from-scratch 138M model trained on this exact corpus reaching 16/16 compile@1 and 16/16 function-correctness on its frozen benchmark. The full per-checkpoint ledger ships so you can see exactly what was measured."),
        ],
    },
    {
        "slug": "attested-text-corpus-v2",
        "name": "Attested Text Corpus v2",
        "price_usd": 499,
        "pack": "corpus",
        "tagline": "25,541 documents / ~1.54B tokens with per-document provenance — Merkle-rooted and witness-signed.",
        "kicker": "Text training data · provenance-gated · Merkle-rooted",
        "records": "25,541 documents / ~1.54B tokens",
        "size_h": "2.45 GB (gzip)",
        "format": "application/gzip",
        "sha256": "92e9af57335910a57e5f50d33564aa07542d6406cb0cde010f0e3c139f2e9e63",
        "pulse": 2516402,
        "provenance": "per-document: pre-1929 PD / source-cleared / operated-substrate",
        "provenance_long": "Each document carries its own provenance basis, cryptographically bound into the Merkle root: 8,643 bright-line pre-1929 public domain, 12,077 source-cleared (Project Gutenberg PD, not independently date-verified), 4,821 oracle-verified code. We report the split exactly and never describe the corpus as fully public-domain.",
        "buy_url": "https://buy.stripe.com/fZudR17kJ54f1S64pR0Fi04",
        "sample": None,
        "ledger": None,
        "keywords": ["public domain training data", "provenance training corpus", "attested text corpus", "merkle-rooted dataset", "pre-1929 public domain text", "clean training data provenance"],
        "highlights": [
            "25,541 documents / ~1.54B tokens, Merkle root <code>92e9af57…</code>, witness-signed at public pulse 2516402",
            "Per-document provenance basis — source, id, year, license — bound into the root",
            "Deduplicated (MinHash/LSH), provenance-gated; five independent verification checks pass",
            "Provenance split stated exactly — never sold as “fully public-domain”",
        ],
        "faq": [
            ("Is this really public domain?", "The provenance is stated exactly per document, not blurred. 8,643 documents are bright-line pre-1929 public domain; 12,077 are source-cleared (Project Gutenberg declares them PD, we did not independently date-verify each); 4,821 are code we generated and machine-verified. We never describe the whole corpus as fully public-domain."),
            ("What am I actually buying if the texts are public?", "The assembly and the proof: 21k books resolved, cleaned, deduplicated and provenance-gated to 25,541 documents, plus a signed, independently re-verifiable provenance chain. Raw public archives cannot answer “prove where each document came from.” This can."),
            ("How do I verify it?", "The signed manifest, the Merkle scheme, and a verifier ship in the package. A second, independent root recompute is provided in Rail. The witness signature is anchored to public entropy pulse 2516402, which you can fetch live."),
            ("What license do I get?", "A single-organization commercial license: train and ship models freely, including commercially. You may not redistribute the corpus itself. See LICENSE.md."),
            ("Can I get the full manifest before buying?", "Yes — email 31zemogyllier@gmail.com for the full document manifest and signed root."),
        ],
    },
]

FONT_PRE = (
    '<link rel="preload" href="/_shared/fonts/MartianMonoVF.dda1215d.woff2" as="font" type="font/woff2" crossorigin media="(prefers-reduced-data: no-preference)">\n'
    '<link rel="preload" href="/_shared/fonts/IBMPlexMono-Regular.6490a869.woff2" as="font" type="font/woff2" crossorigin media="(prefers-reduced-data: no-preference)">'
)
FAVICON = "data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%2064%2064'%3E%3Crect%20width='64'%20height='64'%20fill='%23141414'/%3E%3Ctext%20x='32'%20y='48'%20font-family='ui-monospace,monospace'%20font-size='48'%20fill='%2305e601'%20text-anchor='middle'%3E/%3C/text%3E%3C/svg%3E"


def dataset_jsonld(d):
    dist = [{
        "@type": "DataDownload",
        "encodingFormat": d["format"],
        "contentSize": d["size_h"],
    }]
    if d["sample"]:
        dist.append({"@type": "DataDownload", "encodingFormat": "application/jsonl",
                     "contentUrl": SITE + d["sample"], "name": "Free 200-record sample"})
    return {
        "@context": "https://schema.org",
        "@type": "Dataset",
        "name": d["name"],
        "description": d["tagline"] + " " + d["provenance_long"],
        "url": f"{SITE}/data/{d['slug']}",
        "identifier": f"sha256:{d['sha256']}",
        "keywords": d["keywords"],
        "license": f"{SITE}/data/{d['slug']}#license",
        "isAccessibleForFree": False,
        "creator": {"@type": "Organization", "name": "Ledatic", "url": SITE},
        "provider": {"@type": "Organization", "name": "Ledatic", "url": SITE},
        "distribution": dist,
        "measurementTechnique": "Cryptographic provenance: SHA-256 leaves, Merkle root, Ed25519 witness signature anchored to a public entropy beacon pulse.",
    }


def faq_jsonld(d):
    return {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": [
            {"@type": "Question", "name": q,
             "acceptedAnswer": {"@type": "Answer", "text": a}}
            for q, a in d["faq"]
        ],
    }


def page_html(d):
    free_row = ""
    if d["sample"]:
        free_row = (f'<p class="free reveal">Free before you buy: '
                    f'<a href="{d["sample"]}">200-record sample</a> · '
                    f'<a href="{d["ledger"]}">signed ledger</a></p>')
    else:
        free_row = ('<p class="free reveal">Free before you buy: '
                    '<a href="mailto:31zemogyllier@gmail.com?subject=Attested%20Text%20Corpus%20v2%20manifest">request the full manifest + signed root</a></p>')

    highlights = "\n".join(f"        <li>{h}</li>" for h in d["highlights"])
    faq_html = "\n".join(
        f'      <div class="qa reveal"><h3>{q}</h3><p>{a}</p></div>' for q, a in d["faq"]
    )
    ld = json.dumps(dataset_jsonld(d), ensure_ascii=False)
    faqld = json.dumps(faq_jsonld(d), ensure_ascii=False)
    desc = (d["tagline"] + " Provenance-attested, independently verifiable, single-organization license.").replace('"', "'")

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<meta name="description" content="{desc}">
<meta property="og:type" content="website">
<meta property="og:url" content="{SITE}/data/{d['slug']}">
<meta property="og:title" content="{d['name']} — Ledatic">
<meta property="og:description" content="{desc}">
<meta property="og:image" content="{SITE}/og.png">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{d['name']} — Ledatic">
<meta name="twitter:description" content="{desc}">
<title>{d['name']} — Ledatic</title>
<link rel="canonical" href="{SITE}/data/{d['slug']}">
<link rel="icon" href="{FAVICON}">
<meta name="theme-color" content="#141414">
{FONT_PRE}
<link rel="stylesheet" href="/_shared/tokens.css">
<link rel="stylesheet" href="/_shared/fonts.css">
<link rel="stylesheet" href="/_shared/site.css">
<link rel="stylesheet" href="/_shared/proof.css">
<script type="application/ld+json">{ld}</script>
<script type="application/ld+json">{faqld}</script>
<style>
.nav-side {{ display:flex; align-items:center; gap:1rem; }}
.hero.compact {{ min-height: 42vh; }}
.hero.compact .hero-content {{ padding-top:7rem; padding-bottom:2rem; }}
.hero-content a {{ pointer-events:auto; }}
.specs {{ width:100%; border-collapse:collapse; margin-top:var(--sp-4); font-size:.9rem; }}
.specs td {{ border-bottom:1px solid var(--line); padding:.6rem .4rem; vertical-align:top; }}
.specs td:first-child {{ color:var(--tx-lo); white-space:nowrap; padding-right:var(--sp-4); }}
.buybar {{ display:flex; flex-wrap:wrap; gap:var(--sp-3); align-items:center; margin-top:var(--sp-4); }}
.price-lg {{ font-size:2rem; font-weight:600; }}
.qa {{ border-top:1px solid var(--line); padding-top:var(--sp-3); margin-top:var(--sp-4); }}
.qa h3 {{ font-size:1rem; margin:0 0 .4rem; }}
.qa p {{ margin:0; }}
.free {{ font-size:.85rem; }}
pre.snippet {{ border:1px solid var(--line); padding:var(--sp-4); overflow-x:auto; font-size:.82rem; line-height:1.55; margin:var(--sp-3) 0 0; }}
pre.snippet .c {{ opacity:.55; }}
</style>
</head>
<body>

<nav class="topnav">
  <a class="logo" href="/">Ledatic<span class="accent"> /</span></a>
  <div class="navlinks">
    <a href="/rail">Rail</a>
    <a href="/receipts">Receipts</a>
    <a href="/data">Data</a>
    <div class="navmore">
      <button class="navmore-btn" aria-haspopup="true" aria-expanded="false">Explore &#9662;</button>
      <div class="navmore-menu" role="menu">
        <a href="/verify" role="menuitem">Verify</a>
        <a href="/entropy" role="menuitem">Entropy beacon</a>
        <a href="/system" role="menuitem">System</a>
        <a href="/changelog" role="menuitem">Changelog</a>
        <a href="/physicify" role="menuitem">Physicify</a>
        <a href="/plasma" role="menuitem">Plasma</a>
        <a href="/aliens" role="menuitem">Aliens</a>
        <a href="/work" role="menuitem">Work</a>
        <a href="/manifesto" role="menuitem">Manifesto</a>
      </div>
    </div>
  </div>
  <div class="nav-side">
    <pulse-clock data-endpoint="/entropy/pulse" data-fresh-pulses="5" data-state="unknown">⌁ p#—</pulse-clock>
    <a class="nav-cta" href="/verify">Verify</a>
  </div>
</nav>

<section class="hero compact">
  <div class="scene"><div class="scene-fallback" aria-hidden="true"></div></div>
  <div class="overlay" aria-hidden="true"></div>
  <div class="hero-content">
    <span class="eyebrow fade-up">{d['kicker']}</span>
    <h1 class="hero-title fade-up">{d['name']}</h1>
    <p class="hero-sub fade-up">{d['tagline']}</p>
    <div class="buybar fade-up">
      <span class="price-lg">${d['price_usd']}</span>
      <a class="btn btn-primary" href="{d['buy_url']}" rel="noopener">Buy now</a>
      <a class="btn btn-secondary" href="#verify">Verify first</a>
      <a class="btn btn-secondary" href="/data">All datasets</a>
    </div>
    <p class="trust fade-up">Single-organization license · instant download on purchase · provenance stated exactly</p>
  </div>
</section>

<main>

<section class="section">
  <div class="wrap">
    <span class="chain-link reveal" aria-hidden="true"></span>
    <span class="eyebrow reveal">What it is</span>
    <h2 class="reveal">Training data you can audit before you buy.</h2>
    <ul class="reveal">
{highlights}
    </ul>
    <table class="specs reveal">
      <tr><td>Records</td><td>{d['records']}</td></tr>
      <tr><td>Size</td><td>{d['size_h']}</td></tr>
      <tr><td>SHA-256</td><td><code>{d['sha256']}</code></td></tr>
      <tr><td>Witness pulse</td><td><a href="/entropy/pulse/{d['pulse']}">{d['pulse']}</a> (public entropy beacon)</td></tr>
      <tr><td>Provenance basis</td><td>{d['provenance']}</td></tr>
      <tr><td>License</td><td>Single-organization commercial</td></tr>
    </table>
    {free_row}
  </div>
</section>

<section class="section" id="verify">
  <div class="wrap">
    <span class="chain-link reveal" aria-hidden="true"></span>
    <span class="eyebrow reveal">Check first</span>
    <h2 class="reveal">Run the verification before you spend a dollar.</h2>
    <p class="gloss reveal">{d['provenance_long']}</p>
    <pre class="snippet reveal"><code><span class="c"># the signed provenance chain is public; the data is licensed</span>
curl {SITE}/entropy/pulse/{d['pulse']}   <span class="c"># the witness pulse, live</span>
<span class="c"># after purchase, the included verifier re-checks the hash + every record</span></code></pre>
  </div>
</section>

<section class="section">
  <div class="wrap">
    <span class="chain-link reveal" aria-hidden="true"></span>
    <span class="eyebrow reveal">Questions</span>
    <h2 class="reveal">Straight answers.</h2>
{faq_html}
  </div>
</section>

<section class="section">
  <div class="wrap">
    <div class="buybar">
      <span class="price-lg">${d['price_usd']}</span>
      <a class="btn btn-primary" href="{d['buy_url']}" rel="noopener">Buy {d['name']}</a>
      <a class="btn btn-secondary" href="/data">See the other dataset</a>
    </div>
  </div>
</section>

</main>

<footer class="site-foot">
  <div class="wrap">
    <p class="foot-note" id="license">&copy; 2026 Ledatic · Detroit, MI · single-organization license · <a href="/data">all datasets</a> · <a href="/receipts">Receipts</a> · everything above is verifiable; nothing above asks you to trust it.</p>
  </div>
</footer>

<script src="/_shared/site.js" defer></script>
<script type="module" src="/_shared/pulse-clock.js"></script>
</body>
</html>
"""


def main():
    os.makedirs(OUT, exist_ok=True)
    catalog = []
    sitemap_blocks = []
    for d in CATALOG:
        path = os.path.join(OUT, f"{d['slug']}.html")
        with open(path, "w") as f:
            f.write(page_html(d))
        print("wrote", os.path.relpath(path))
        catalog.append({
            "name": d["name"], "slug": d["slug"], "price_usd": d["price_usd"],
            "url": f"{SITE}/data/{d['slug']}", "buy_url": d["buy_url"],
            "records": d["records"], "size": d["size_h"], "format": d["format"],
            "sha256": d["sha256"], "witness_pulse": d["pulse"],
            "provenance_basis": d["provenance"], "license": "single-organization commercial",
        })
        sitemap_blocks.append(
            f"  <url>\n    <loc>{SITE}/data/{d['slug']}</loc>\n"
            f"    <lastmod>2026-07-02</lastmod>\n    <changefreq>weekly</changefreq>\n"
            f"    <priority>0.8</priority>\n  </url>"
        )
    cat = {"catalog": "ledatic-attested-data", "updated": "2026-07-02",
           "verify_note": "Every listing's provenance chain is independently re-verifiable; see each dataset page.",
           "datasets": catalog}
    with open(os.path.join(OUT, "catalog.json"), "w") as f:
        json.dump(cat, f, indent=2)
    print("wrote", os.path.relpath(os.path.join(OUT, "catalog.json")))
    print("\n--- sitemap <url> blocks to add ---")
    print("\n".join(sitemap_blocks))


if __name__ == "__main__":
    main()
